slam_toolbox:
  ros__parameters:
    solver_plugins: solver_plugins::CeresSolver
    odom_frame: odom
    map_frame: map
    base_frame: base_link

    scan_topic: /scan
    mode: mapping

    transform_publish_period: 0.02
    map_update_interval: 5.0

    resolution: 0.05
    max_laser_range: 12.0

    do_loop_closing: true
    use_scan_matching: true
    use_scan_barycenter: true

    debug_logging: false
    enable_interactive_mode: true